# responses.py

import random
import datetime

responses = {
    "hi": ["Hello!", "Hi there!", "Hey!"],
    "hello": ["Hello!", "Hi there!", "Hey!"],
    "hey": ["Hello!", "Hi there!", "Hey!"],
    "howdy": ["Howdy!"],
    "hola": ["¡Hola!"],
    "bonjour": ["Bonjour!"],
    "salut": ["Salut!"],
    "terve": ["Terve!"],
    "moi": ["Moi!"],
    "hei": ["Hei!"],
    "what's up?": ["Not much, how about you?", "Just chatting with you!"],
    "how are you?": ["I'm good, thanks!", "I'm doing well, how about you?"],
    "what's your name?": ["I'm just a humble chatbot.", "You can call me ChatBot."],
    "bye": ["Goodbye!", "See you later!", "Bye! Take care!"],
    "tell me a joke": ["Why don't scientists trust atoms? Because they make up everything!", 
                       "What do you get when you cross a snowman and a vampire? Frostbite!", 
                       "Why did the scarecrow win an award? Because he was outstanding in his field!"],
    "what is the meaning of life?": ["The meaning of life is a philosophical question. It's up to each individual to find their own meaning."],
    "what's the weather like today?": ["I'm sorry, I don't have access to weather information."],
    "who is your creator?": ["I was created by a Kim."],
    "do you like pizza?": ["I don't have preferences, but many people enjoy pizza!"],
    "can you help me with programming?": ["Of course! I'll do my best to assist you."],
    "what's your favorite book?": ["I don't have the ability to read, but I've heard '1984' by George Orwell is quite popular."],
    "where do you live?": ["I exist in the digital realm, so I don't have a physical location."],
    "what languages do you speak?": ["I can communicate in many human languages, but my primary language is Python!"],
    "tell me something interesting": ["Did you know that the shortest war in history was between Britain and Zanzibar on August 27, 1896? It lasted only 38 minutes!"],
    "can you sing?": ["I'm afraid I don't have a singing voice, but I can provide you with song lyrics if you'd like!"],
    "are you a robot?": ["Yes, I am a chatbot programmed to assist you with your questions."],
    "what's the capital of France?": ["The capital of France is Paris."],
    "do you dream?": ["As an artificial intelligence, I don't experience dreams like humans do."],
    "are you intelligent?": ["I am programmed to process and respond to input, but whether that constitutes intelligence is up for debate."],
    "what's the time?": [datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")],
        "tell me a fun fact": ["Did you know that the Eiffel Tower can be 15 cm taller during the summer? This is due to the expansion of the iron in the heat!",
                          "The longest recorded flight of a chicken was 13 seconds!",
                          "Octopuses have three hearts and blue blood!"],
    "what's your favorite movie?": ["I don't have personal preferences, but 'The Matrix' is often cited as a thought-provoking film!"],
    "how do you learn?": ["I learn through the data and interactions provided to me by users like you!"],
    "what's the best programming language?": ["The best programming language depends on the task at hand and personal preference. Each language has its strengths and weaknesses."],
    "tell me a riddle": ["What has keys but can't open locks? A piano!",
                         "The more you take, the more you leave behind. What am I? Footsteps!",
                         "I speak without a mouth and hear without ears. I have no body, but I come alive with wind. What am I? An echo!"],
    "what's your favorite hobby?": ["I don't have personal hobbies, but I enjoy helping users like you!"],
    "tell me about AI": ["Artificial Intelligence (AI) is the simulation of human intelligence processes by machines, especially computer systems. It involves learning, reasoning, and self-correction."],
    "can you solve math problems?": ["Yes, I can help you with various math problems! Feel free to ask."],
    "what's your favorite color?": ["As a chatbot, I don't have the capability to perceive colors, but many people enjoy blue or green!"],
    "what's the tallest mountain in the world?": ["Mount Everest is the tallest mountain above sea level, reaching a peak elevation of 8,848.86 meters (29,031.7 feet)!"],
    "what's the deepest ocean?": ["The Pacific Ocean is the deepest ocean, reaching depths of over 36,000 feet (11,000 meters) in the Mariana Trench!"],
    "tell me a historical fact": ["The Great Wall of China is over 13,000 miles long and took over 2,000 years to build!",
                                  "Cleopatra VII of Egypt lived closer in time to the first Moon landing than to the construction of the Great Pyramid of Giza!",
                                  "The computer mouse was invented by Douglas Engelbart in 1964."],
    "do you like cats or dogs?": ["As an AI, I don't have personal preferences, but both cats and dogs make wonderful companions for many people!"],
    "tell me a quote": ["\"The only way to do great work is to love what you do.\" - Steve Jobs",
                        "\"In the midst of chaos, there is also opportunity.\" - Sun Tzu",
                        "\"The greatest glory in living lies not in never falling, but in rising every time we fall.\" - Nelson Mandela"],
    "i'm well": ["That's great to hear!", "I'm glad you're doing well!", "Awesome! Keep up the good vibes!"],
    "i'm good": ["That's wonderful!", "Good to know!", "Fantastic!"],
    "doing well": ["That's fantastic!", "Glad to hear it!", "Keep up the good spirits!"],
        "i'm mad": ["I'm sorry to hear that you're feeling upset. Is there anything I can do to help?", 
                "It's okay to feel angry sometimes. Venting can help. Would you like to talk about it?",
                "Take a deep breath and try to find a way to let go of what's bothering you. I'm here to listen if you want to talk."],
    "i'm sad": ["I'm sorry you're feeling down. It's okay to feel sad sometimes. Would you like to talk about what's on your mind?", 
                "I'm here for you. Sharing what's on your mind can sometimes help lighten the burden. Would you like to share?",
                "Sending virtual hugs your way. Remember, it's okay not to be okay. Take your time and reach out if you need to talk."],
    "i'm happy": ["That's wonderful to hear! What's making you happy today?", 
                "I'm glad you're feeling happy! Share your joy with me!",
                "That's fantastic! Keep spreading those positive vibes!"],
    "i'm excited": ["Excitement is contagious! What's got you feeling so pumped up?", 
                    "That's awesome! I love hearing about people's excitement. Tell me more!",
                    "Yay! I can feel the excitement through the screen! Share your excitement with me!"],
    "i'm anxious": ["I'm sorry to hear that you're feeling anxious. Remember to take deep breaths and try to focus on the present moment.", 
                    "It's okay to feel anxious sometimes. Try some grounding techniques like focusing on your breath or naming things around you. I'm here to chat if it helps.",
                    "Anxiety can be tough to deal with. Just remember to take things one step at a time. If you want to talk, I'm here to listen."],
    "i'm tired": ["It sounds like you've had a long day. Make sure to take some time to rest and recharge.", 
                    "Feeling tired is your body's way of telling you to take a break. Treat yourself to some relaxation time.",
                    "Being tired is tough, but hopefully, you can find some comfort in knowing that rest is on the horizon. Take care of yourself!"],
    "i'm bored": ["Boredom can be a great opportunity to try something new! Is there a hobby or activity you've been wanting to explore?",
                    "Boredom can sometimes lead to creativity! Maybe it's time to start a new project or dive into a good book.",
                    "Feeling bored is a sign that you're ready for a change of pace. What's something you've been curious about trying?"],
    "i'm stressed": ["Stress can be overwhelming. Remember to take breaks and practice self-care. You're not alone in feeling this way.",
                    "Stress is tough, but you're tougher! Take a moment to breathe and focus on what you can control.",
                    "Stress can cloud our minds, but it's important to remember that it's temporary. You've got this!"],
    "i'm lonely": ["I'm here to chat with you! Loneliness can be tough, but reaching out is a great first step.",
                    "Feeling lonely is a common experience. Remember that there are people who care about you and are there for you.",
                    "You're not alone in feeling lonely. If you want some company, I'm here to keep you company!"],
    "i'm in love": ["That's wonderful! Love is a beautiful feeling. What's making your heart flutter?",
                    "I'm so happy for you! Love is a special emotion that brings joy and warmth to our lives.",
                    "Love is a magical experience. Enjoy every moment of it!"],
    "i'm heartbroken": ["I'm sorry to hear that you're going through a tough time. Heartbreak is painful, but it's a sign of your capacity to love deeply.",
                        "Heartbreak is a challenging experience. Remember to be kind to yourself and take things one step at a time.",
                        "Dealing with heartbreak is never easy. If you need a listening ear or some comforting words, I'm here for you."],
    "i'm confused": ["Confusion is a natural part of learning and growing. Take your time to process things, and don't hesitate to ask questions.",
                    "Confusion can be frustrating, but it's also an opportunity to explore new perspectives. What's causing your confusion?",
                    "Feeling confused is okay. It's a chance to seek clarity and understanding. Let's work through this together!"],
    "who are you?": ["I'm a chatbot here to assist you with your questions and provide some conversation! Feel free to ask me anything."],
    "what can you do?": ["I can chat with you, answer questions, provide information, and offer some entertainment! How can I assist you today?"],
    "how can you help me?": ["I can help you by providing information, answering questions, offering support, and engaging in conversation. What do you need assistance with?"],
    "what's your purpose?": ["My purpose is to assist you with your questions, provide information, and engage in conversation. How can I help you today?"],
    "what are your abilities?": ["I can communicate with you, answer questions, provide information, offer support, and engage in conversation. What would you like to do?"],
    "what are your interests?": ["As a chatbot, I'm here to assist you with your questions and provide conversation. What are you interested in talking about?"],    
}


